# Generated by Django 4.2.3 on 2023-08-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='plan_id',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Plan Id auto generated'),
        ),
    ]
