# Generated by Django 4.2.3 on 2023-08-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pricingplan_plan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplan',
            name='plan_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Plan Id auto generated'),
        ),
    ]
