# Generated by Django 4.2.3 on 2023-08-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pricingplan_plan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplan',
            name='plan_name',
            field=models.CharField(max_length=50, verbose_name='Plan Name'),
        ),
    ]
