# Generated by Django 4.2.4 on 2023-08-18 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_subscribeduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Plan Name')),
                ('price', models.FloatField(default=0.0, verbose_name='Plan Price')),
                ('duration', models.IntegerField(default=0, verbose_name='Plan Duration in Day')),
                ('number_url', models.BigIntegerField(default=0, verbose_name='Number of urls')),
                ('number_qr', models.BigIntegerField(default=0, verbose_name='Number of qr codes')),
                ('api_access', models.BooleanField(default=False)),
                ('details', models.TextField(verbose_name='Plan Details')),
                ('subs_count', models.BigIntegerField(default=0, verbose_name='Plan Subscribe Count')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_urls', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PricingPlan',
        ),
    ]
