# Generated by Django 4.2.4 on 2023-08-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_user_qrs_subscription_used_qrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.IntegerField(choices=[('1', '365'), ('2', '730'), ('3', '1095'), ('4', '1460'), ('5', '1825')], default=1, verbose_name='Plan Duration in Day'),
        ),
    ]
