# Generated by Django 4.2.4 on 2023-09-06 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_subscription_razorpay_payment_id_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='razorpay_payment_id',
        ),
    ]
