# Generated by Django 4.2.4 on 2023-09-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_userloginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginhistory',
            name='browser',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userloginhistory',
            name='os',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userloginhistory',
            name='device_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
