# Generated by Django 4.2.4 on 2023-08-21 19:26

from django.db import migrations, models
import functions.validators


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0002_excelfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='excelsheet',
            field=models.FileField(upload_to='Excel_Files', validators=[functions.validators.validate_xlsx_extension], verbose_name='Upload Excel Sheet'),
        ),
    ]
