# Generated by Django 4.2.4 on 2023-08-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0004_bulkurlshort'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkurlshort',
            name='url_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Url Related Title'),
        ),
    ]
