# Generated by Django 4.2.4 on 2023-09-12 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0007_alter_qrcode_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlHitDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Visitor IP')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='Country Code')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('hit_time', models.DateTimeField(blank=True, null=True, verbose_name='Hit Time')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='Browser')),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='Operating System')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hit_details', to='functions.url')),
            ],
        ),
    ]
