# Generated by Django 4.2.4 on 2023-09-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0009_alter_urlhitdetail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlhitdetail',
            name='country',
            field=models.CharField(blank=True, default='N/A', max_length=2, null=True, verbose_name='Country Code'),
        ),
    ]
